version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    target-branch: dev

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    target-branch: dev
