name: Docs to Github Pages
on:
  push:
    branches:
    - 'test-gh-pages'

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch beta
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4.6.1
        with:
          cache: pip
          cache-dependency-path: requirements/docs.txt
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade --requirement requirements/docs.txt
          python -m pip install .
      - name: Build docs
        run: |
          make gh-pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
      - name: Deploy pages
        uses: actions/deploy-pages@v2.0.1
